// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ranking.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 分数操作类型（RecordScore 使用；消息定义见本文件，摄入服务在 ranking_ingest.proto 复用）
type ScoreOp int32

const (
	ScoreOp_SCORE_OP_UNSPECIFIED ScoreOp = 0
	ScoreOp_SCORE_OP_INCREMENT   ScoreOp = 1 // 增量（delta）
	ScoreOp_SCORE_OP_SET         ScoreOp = 2 // 设置绝对值（score）
)

// Enum value maps for ScoreOp.
var (
	ScoreOp_name = map[int32]string{
		0: "SCORE_OP_UNSPECIFIED",
		1: "SCORE_OP_INCREMENT",
		2: "SCORE_OP_SET",
	}
	ScoreOp_value = map[string]int32{
		"SCORE_OP_UNSPECIFIED": 0,
		"SCORE_OP_INCREMENT":   1,
		"SCORE_OP_SET":         2,
	}
)

func (x ScoreOp) Enum() *ScoreOp {
	p := new(ScoreOp)
	*p = x
	return p
}

func (x ScoreOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScoreOp) Descriptor() protoreflect.EnumDescriptor {
	return file_ranking_proto_enumTypes[0].Descriptor()
}

func (ScoreOp) Type() protoreflect.EnumType {
	return &file_ranking_proto_enumTypes[0]
}

func (x ScoreOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScoreOp.Descriptor instead.
func (ScoreOp) EnumDescriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{0}
}

type GetRankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`   // 榜单键，如 "board:user:fans"
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"` // 榜单成员 = 业务主键字符串（文章/用户 ID 转 string）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankRequest) Reset() {
	*x = GetRankRequest{}
	mi := &file_ranking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankRequest) ProtoMessage() {}

func (x *GetRankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankRequest.ProtoReflect.Descriptor instead.
func (*GetRankRequest) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{0}
}

func (x *GetRankRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *GetRankRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type GetRankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0=成功，非 0=失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 结果描述
	Rank          int64                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`      // 1-based；0 表示未上榜
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`   // 当前分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankResponse) Reset() {
	*x = GetRankResponse{}
	mi := &file_ranking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankResponse) ProtoMessage() {}

func (x *GetRankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResponse.ProtoReflect.Descriptor instead.
func (*GetRankResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{1}
}

func (x *GetRankResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRankResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRankResponse) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *GetRankResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`   // 榜单键，如 "board:user:fans"
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"` // 榜单成员 = 业务主键字符串（文章/用户 ID 转 string）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreRequest) Reset() {
	*x = GetScoreRequest{}
	mi := &file_ranking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreRequest) ProtoMessage() {}

func (x *GetScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreRequest.ProtoReflect.Descriptor instead.
func (*GetScoreRequest) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{2}
}

func (x *GetScoreRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *GetScoreRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type GetScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0=成功，非 0=失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 结果描述
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`   // 当前分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScoreResponse) Reset() {
	*x = GetScoreResponse{}
	mi := &file_ranking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScoreResponse) ProtoMessage() {}

func (x *GetScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScoreResponse.ProtoReflect.Descriptor instead.
func (*GetScoreResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{3}
}

func (x *GetScoreResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RecordScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`                    // 榜单键，如 "board:user:fans"
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`                  // 榜单成员 = 业务主键字符串（文章/用户 ID 转 string）
	Delta         float64                `protobuf:"fixed64,3,opt,name=delta,proto3" json:"delta,omitempty"`                  // SCORE_OP_INCREMENT 使用
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`                  // SCORE_OP_SET 使用
	Op            ScoreOp                `protobuf:"varint,5,opt,name=op,proto3,enum=ranking.v1.ScoreOp" json:"op,omitempty"` // 分数操作类型（见 ScoreOp）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordScoreRequest) Reset() {
	*x = RecordScoreRequest{}
	mi := &file_ranking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordScoreRequest) ProtoMessage() {}

func (x *RecordScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordScoreRequest.ProtoReflect.Descriptor instead.
func (*RecordScoreRequest) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{4}
}

func (x *RecordScoreRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *RecordScoreRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *RecordScoreRequest) GetDelta() float64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *RecordScoreRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecordScoreRequest) GetOp() ScoreOp {
	if x != nil {
		return x.Op
	}
	return ScoreOp_SCORE_OP_UNSPECIFIED
}

type RecordScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0=成功，非 0=失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 结果描述
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`   // 操作后的最新分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordScoreResponse) Reset() {
	*x = RecordScoreResponse{}
	mi := &file_ranking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordScoreResponse) ProtoMessage() {}

func (x *RecordScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordScoreResponse.ProtoReflect.Descriptor instead.
func (*RecordScoreResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{5}
}

func (x *RecordScoreResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RecordScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecordScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// ScoreItem 批量摄入的单项：member + 绝对值分数。
type ScoreItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"` // 榜单成员 = 业务主键字符串（文章/用户 ID 转 string）
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"` // 绝对值分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreItem) Reset() {
	*x = ScoreItem{}
	mi := &file_ranking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreItem) ProtoMessage() {}

func (x *ScoreItem) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreItem.ProtoReflect.Descriptor instead.
func (*ScoreItem) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreItem) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *ScoreItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type BatchSetScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`                                 // 榜单键
	Items         []*ScoreItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`                                 // 待写入的成员与绝对值分数
	PruneOthers   bool                   `protobuf:"varint,3,opt,name=prune_others,json=pruneOthers,proto3" json:"prune_others,omitempty"` // true=移除 ZSET 中不在 items 内的旧成员（完整快照回填时开启）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetScoreRequest) Reset() {
	*x = BatchSetScoreRequest{}
	mi := &file_ranking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetScoreRequest) ProtoMessage() {}

func (x *BatchSetScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetScoreRequest.ProtoReflect.Descriptor instead.
func (*BatchSetScoreRequest) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{7}
}

func (x *BatchSetScoreRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *BatchSetScoreRequest) GetItems() []*ScoreItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchSetScoreRequest) GetPruneOthers() bool {
	if x != nil {
		return x.PruneOthers
	}
	return false
}

type BatchSetScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0=成功，非 0=失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 结果描述
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`    // 成功写入的成员数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSetScoreResponse) Reset() {
	*x = BatchSetScoreResponse{}
	mi := &file_ranking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSetScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSetScoreResponse) ProtoMessage() {}

func (x *BatchSetScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSetScoreResponse.ProtoReflect.Descriptor instead.
func (*BatchSetScoreResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{8}
}

func (x *BatchSetScoreResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchSetScoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchSetScoreResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// BoardConfig 由业务方通过 RegisterBoard 注册，声明该 board 如何展示与是否可跳转。
// ranking-service 仅按配置行事，不感知任何业务字段，新增榜单无需改动核心代码。
type BoardConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Board            string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`                                               // 榜单键，如 "board:user:fans"
	DecoratorType    string                 `protobuf:"bytes,2,opt,name=decorator_type,json=decoratorType,proto3" json:"decorator_type,omitempty"`          // 固定 "remote"：回调业务服务（实现 decorator.v0.Decorator）
	DecoratorService string                 `protobuf:"bytes,4,opt,name=decorator_service,json=decoratorService,proto3" json:"decorator_service,omitempty"` // decorator_type=remote 时：consul 服务名，如 "article-service"
	DecoratorMethod  string                 `protobuf:"bytes,5,opt,name=decorator_method,json=decoratorMethod,proto3" json:"decorator_method,omitempty"`    // decorator_type=remote 时：方法名，默认 "Decorate"
	LinkTemplate     string                 `protobuf:"bytes,6,opt,name=link_template,json=linkTemplate,proto3" json:"link_template,omitempty"`             // 跳转模板，如 "/space/{member}"；空=不跳转
	CacheTtlSec      int32                  `protobuf:"varint,7,opt,name=cache_ttl_sec,json=cacheTtlSec,proto3" json:"cache_ttl_sec,omitempty"`             // 富化结果缓存秒数，<=0 用默认
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BoardConfig) Reset() {
	*x = BoardConfig{}
	mi := &file_ranking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardConfig) ProtoMessage() {}

func (x *BoardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardConfig.ProtoReflect.Descriptor instead.
func (*BoardConfig) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{9}
}

func (x *BoardConfig) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *BoardConfig) GetDecoratorType() string {
	if x != nil {
		return x.DecoratorType
	}
	return ""
}

func (x *BoardConfig) GetDecoratorService() string {
	if x != nil {
		return x.DecoratorService
	}
	return ""
}

func (x *BoardConfig) GetDecoratorMethod() string {
	if x != nil {
		return x.DecoratorMethod
	}
	return ""
}

func (x *BoardConfig) GetLinkTemplate() string {
	if x != nil {
		return x.LinkTemplate
	}
	return ""
}

func (x *BoardConfig) GetCacheTtlSec() int32 {
	if x != nil {
		return x.CacheTtlSec
	}
	return 0
}

// RankItem 业务无关的榜单条目：member 为业务 ID，display 为不透明展示结构，link 为跳转链接。
type RankItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`   // 业务主键字符串（文章/用户 ID 转 string）
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`   // 该成员当前分数
	Rank          int64                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`      // 1-based；0 表示未上榜
	Display       *structpb.Struct       `protobuf:"bytes,4,opt,name=display,proto3" json:"display,omitempty"` // 不透明展示结构（来自 decorator，ranking 透传）
	Link          string                 `protobuf:"bytes,5,opt,name=link,proto3" json:"link,omitempty"`       // 已渲染的跳转链接（空=不跳转）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankItem) Reset() {
	*x = RankItem{}
	mi := &file_ranking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankItem) ProtoMessage() {}

func (x *RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankItem.ProtoReflect.Descriptor instead.
func (*RankItem) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{10}
}

func (x *RankItem) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *RankItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankItem) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankItem) GetDisplay() *structpb.Struct {
	if x != nil {
		return x.Display
	}
	return nil
}

func (x *RankItem) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type RegisterBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *BoardConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBoardRequest) Reset() {
	*x = RegisterBoardRequest{}
	mi := &file_ranking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBoardRequest) ProtoMessage() {}

func (x *RegisterBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBoardRequest.ProtoReflect.Descriptor instead.
func (*RegisterBoardRequest) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterBoardRequest) GetConfig() *BoardConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type RegisterBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0=成功，非 0=失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 结果描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBoardResponse) Reset() {
	*x = RegisterBoardResponse{}
	mi := &file_ranking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBoardResponse) ProtoMessage() {}

func (x *RegisterBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBoardResponse.ProtoReflect.Descriptor instead.
func (*RegisterBoardResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterBoardResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterBoardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`  // 榜单键，如 "board:user:fans"
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 返回条数上限（默认 10，最大 100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingRequest) Reset() {
	*x = GetRankingRequest{}
	mi := &file_ranking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingRequest) ProtoMessage() {}

func (x *GetRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingRequest.ProtoReflect.Descriptor instead.
func (*GetRankingRequest) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{13}
}

func (x *GetRankingRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *GetRankingRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRankingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 0=成功，非 0=失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 结果描述
	Items         []*RankItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`     // 榜单条目列表（含展示信息与跳转链接）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRankingResponse) Reset() {
	*x = GetRankingResponse{}
	mi := &file_ranking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankingResponse) ProtoMessage() {}

func (x *GetRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ranking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankingResponse.ProtoReflect.Descriptor instead.
func (*GetRankingResponse) Descriptor() ([]byte, []int) {
	return file_ranking_proto_rawDescGZIP(), []int{14}
}

func (x *GetRankingResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetRankingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRankingResponse) GetItems() []*RankItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_ranking_proto protoreflect.FileDescriptor

const file_ranking_proto_rawDesc = "" +
	"\n" +
	"\rranking.proto\x12\n" +
	"ranking.v1\x1a\x1cgoogle/protobuf/struct.proto\">\n" +
	"\x0eGetRankRequest\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\"i\n" +
	"\x0fGetRankResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x03R\x04rank\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"?\n" +
	"\x0fGetScoreRequest\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\"V\n" +
	"\x10GetScoreResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"\x93\x01\n" +
	"\x12RecordScoreRequest\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x01R\x05delta\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12#\n" +
	"\x02op\x18\x05 \x01(\x0e2\x13.ranking.v1.ScoreOpR\x02op\"Y\n" +
	"\x13RecordScoreResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"9\n" +
	"\tScoreItem\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"|\n" +
	"\x14BatchSetScoreRequest\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.ranking.v1.ScoreItemR\x05items\x12!\n" +
	"\fprune_others\x18\x03 \x01(\bR\vpruneOthers\"[\n" +
	"\x15BatchSetScoreResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"\xeb\x01\n" +
	"\vBoardConfig\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12%\n" +
	"\x0edecorator_type\x18\x02 \x01(\tR\rdecoratorType\x12+\n" +
	"\x11decorator_service\x18\x04 \x01(\tR\x10decoratorService\x12)\n" +
	"\x10decorator_method\x18\x05 \x01(\tR\x0fdecoratorMethod\x12#\n" +
	"\rlink_template\x18\x06 \x01(\tR\flinkTemplate\x12\"\n" +
	"\rcache_ttl_sec\x18\a \x01(\x05R\vcacheTtlSec\"\x93\x01\n" +
	"\bRankItem\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x03R\x04rank\x121\n" +
	"\adisplay\x18\x04 \x01(\v2\x17.google.protobuf.StructR\adisplay\x12\x12\n" +
	"\x04link\x18\x05 \x01(\tR\x04link\"G\n" +
	"\x14RegisterBoardRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.ranking.v1.BoardConfigR\x06config\"E\n" +
	"\x15RegisterBoardResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x11GetRankingRequest\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"n\n" +
	"\x12GetRankingResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x05items\x18\x03 \x03(\v2\x14.ranking.v1.RankItemR\x05items*M\n" +
	"\aScoreOp\x12\x18\n" +
	"\x14SCORE_OP_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SCORE_OP_INCREMENT\x10\x01\x12\x10\n" +
	"\fSCORE_OP_SET\x10\x022\xe8\x01\n" +
	"\x0eRankingService\x12K\n" +
	"\n" +
	"GetRanking\x12\x1d.ranking.v1.GetRankingRequest\x1a\x1e.ranking.v1.GetRankingResponse\x12B\n" +
	"\aGetRank\x12\x1a.ranking.v1.GetRankRequest\x1a\x1b.ranking.v1.GetRankResponse\x12E\n" +
	"\bGetScore\x12\x1b.ranking.v1.GetScoreRequest\x1a\x1c.ranking.v1.GetScoreResponseB1Z/github.com/mysunshines/blog-ranking/proto/pb/v1b\x06proto3"

var (
	file_ranking_proto_rawDescOnce sync.Once
	file_ranking_proto_rawDescData []byte
)

func file_ranking_proto_rawDescGZIP() []byte {
	file_ranking_proto_rawDescOnce.Do(func() {
		file_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ranking_proto_rawDesc), len(file_ranking_proto_rawDesc)))
	})
	return file_ranking_proto_rawDescData
}

var file_ranking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ranking_proto_goTypes = []any{
	(ScoreOp)(0),                  // 0: ranking.v1.ScoreOp
	(*GetRankRequest)(nil),        // 1: ranking.v1.GetRankRequest
	(*GetRankResponse)(nil),       // 2: ranking.v1.GetRankResponse
	(*GetScoreRequest)(nil),       // 3: ranking.v1.GetScoreRequest
	(*GetScoreResponse)(nil),      // 4: ranking.v1.GetScoreResponse
	(*RecordScoreRequest)(nil),    // 5: ranking.v1.RecordScoreRequest
	(*RecordScoreResponse)(nil),   // 6: ranking.v1.RecordScoreResponse
	(*ScoreItem)(nil),             // 7: ranking.v1.ScoreItem
	(*BatchSetScoreRequest)(nil),  // 8: ranking.v1.BatchSetScoreRequest
	(*BatchSetScoreResponse)(nil), // 9: ranking.v1.BatchSetScoreResponse
	(*BoardConfig)(nil),           // 10: ranking.v1.BoardConfig
	(*RankItem)(nil),              // 11: ranking.v1.RankItem
	(*RegisterBoardRequest)(nil),  // 12: ranking.v1.RegisterBoardRequest
	(*RegisterBoardResponse)(nil), // 13: ranking.v1.RegisterBoardResponse
	(*GetRankingRequest)(nil),     // 14: ranking.v1.GetRankingRequest
	(*GetRankingResponse)(nil),    // 15: ranking.v1.GetRankingResponse
	(*structpb.Struct)(nil),       // 16: google.protobuf.Struct
}
var file_ranking_proto_depIdxs = []int32{
	0,  // 0: ranking.v1.RecordScoreRequest.op:type_name -> ranking.v1.ScoreOp
	7,  // 1: ranking.v1.BatchSetScoreRequest.items:type_name -> ranking.v1.ScoreItem
	16, // 2: ranking.v1.RankItem.display:type_name -> google.protobuf.Struct
	10, // 3: ranking.v1.RegisterBoardRequest.config:type_name -> ranking.v1.BoardConfig
	11, // 4: ranking.v1.GetRankingResponse.items:type_name -> ranking.v1.RankItem
	14, // 5: ranking.v1.RankingService.GetRanking:input_type -> ranking.v1.GetRankingRequest
	1,  // 6: ranking.v1.RankingService.GetRank:input_type -> ranking.v1.GetRankRequest
	3,  // 7: ranking.v1.RankingService.GetScore:input_type -> ranking.v1.GetScoreRequest
	15, // 8: ranking.v1.RankingService.GetRanking:output_type -> ranking.v1.GetRankingResponse
	2,  // 9: ranking.v1.RankingService.GetRank:output_type -> ranking.v1.GetRankResponse
	4,  // 10: ranking.v1.RankingService.GetScore:output_type -> ranking.v1.GetScoreResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ranking_proto_init() }
func file_ranking_proto_init() {
	if File_ranking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ranking_proto_rawDesc), len(file_ranking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ranking_proto_goTypes,
		DependencyIndexes: file_ranking_proto_depIdxs,
		EnumInfos:         file_ranking_proto_enumTypes,
		MessageInfos:      file_ranking_proto_msgTypes,
	}.Build()
	File_ranking_proto = out.File
	file_ranking_proto_goTypes = nil
	file_ranking_proto_depIdxs = nil
}
