// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ranking_ingest.proto

// ============================================================================
// Ranking 内部摄入契约（v0）：与对外读接口（ranking.v1.RankingService）分离。
// ----------------------------------------------------------------------------
// 约定：所有「服务间内部调用」的 gRPC 接口统一置于 v0 包（ranking.v0.*），
// 与对外 C 端接口（v1/v2）在命名与部署上彻底隔离：
//   - 公网网关（Gateway）按 DeriveGRPCService 仅代理 *.v1.* 服务，v0 天然不进公网入口；
//   - v0 仅由内网服务经 Consul 直连 gRPC 调用，完全信任内网、不做应用层鉴权，
//     安全性依赖 gRPC 端口仅对内网开放（不暴露公网）。
// ============================================================================

package v0

import (
	v1 "github.com/mysunshines/blog-ranking/proto/pb/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ranking_ingest_proto protoreflect.FileDescriptor

const file_ranking_ingest_proto_rawDesc = "" +
	"\n" +
	"\x14ranking_ingest.proto\x12\n" +
	"ranking.v0\x1a\rranking.proto2\x8c\x02\n" +
	"\x0eRankingService\x12N\n" +
	"\vRecordScore\x12\x1e.ranking.v1.RecordScoreRequest\x1a\x1f.ranking.v1.RecordScoreResponse\x12T\n" +
	"\rBatchSetScore\x12 .ranking.v1.BatchSetScoreRequest\x1a!.ranking.v1.BatchSetScoreResponse\x12T\n" +
	"\rRegisterBoard\x12 .ranking.v1.RegisterBoardRequest\x1a!.ranking.v1.RegisterBoardResponseB1Z/github.com/mysunshines/blog-ranking/proto/pb/v0b\x06proto3"

var file_ranking_ingest_proto_goTypes = []any{
	(*v1.RecordScoreRequest)(nil),    // 0: ranking.v1.RecordScoreRequest
	(*v1.BatchSetScoreRequest)(nil),  // 1: ranking.v1.BatchSetScoreRequest
	(*v1.RegisterBoardRequest)(nil),  // 2: ranking.v1.RegisterBoardRequest
	(*v1.RecordScoreResponse)(nil),   // 3: ranking.v1.RecordScoreResponse
	(*v1.BatchSetScoreResponse)(nil), // 4: ranking.v1.BatchSetScoreResponse
	(*v1.RegisterBoardResponse)(nil), // 5: ranking.v1.RegisterBoardResponse
}
var file_ranking_ingest_proto_depIdxs = []int32{
	0, // 0: ranking.v0.RankingService.RecordScore:input_type -> ranking.v1.RecordScoreRequest
	1, // 1: ranking.v0.RankingService.BatchSetScore:input_type -> ranking.v1.BatchSetScoreRequest
	2, // 2: ranking.v0.RankingService.RegisterBoard:input_type -> ranking.v1.RegisterBoardRequest
	3, // 3: ranking.v0.RankingService.RecordScore:output_type -> ranking.v1.RecordScoreResponse
	4, // 4: ranking.v0.RankingService.BatchSetScore:output_type -> ranking.v1.BatchSetScoreResponse
	5, // 5: ranking.v0.RankingService.RegisterBoard:output_type -> ranking.v1.RegisterBoardResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ranking_ingest_proto_init() }
func file_ranking_ingest_proto_init() {
	if File_ranking_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ranking_ingest_proto_rawDesc), len(file_ranking_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ranking_ingest_proto_goTypes,
		DependencyIndexes: file_ranking_ingest_proto_depIdxs,
	}.Build()
	File_ranking_ingest_proto = out.File
	file_ranking_ingest_proto_goTypes = nil
	file_ranking_ingest_proto_depIdxs = nil
}
