// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: ranking_ingest.proto

// ============================================================================
// Ranking 内部摄入契约（v0）：与对外读接口（ranking.v1.RankingService）分离。
// ----------------------------------------------------------------------------
// 约定：所有「服务间内部调用」的 gRPC 接口统一置于 v0 包（ranking.v0.*），
// 与对外 C 端接口（v1/v2）在命名与部署上彻底隔离：
//   - 公网网关（Gateway）按 DeriveGRPCService 仅代理 *.v1.* 服务，v0 天然不进公网入口；
//   - v0 仅由内网服务经 Consul 直连 gRPC 调用，完全信任内网、不做应用层鉴权，
//     安全性依赖 gRPC 端口仅对内网开放（不暴露公网）。
// ============================================================================

package v0

import (
	context "context"
	v1 "github.com/mysunshines/blog-ranking/proto/pb/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RankingService_RecordScore_FullMethodName   = "/ranking.v0.RankingService/RecordScore"
	RankingService_BatchSetScore_FullMethodName = "/ranking.v0.RankingService/BatchSetScore"
	RankingService_RegisterBoard_FullMethodName = "/ranking.v0.RankingService/RegisterBoard"
)

// RankingServiceClient is the client API for RankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RankingService 内部摄入接口（ranking.v0，仅内网、仅受信服务）：
// 业务方（article/comment/user）推送分数变更 + 声明榜单展示配置。
type RankingServiceClient interface {
	// 推送分数变更（增量或绝对值）。
	RecordScore(ctx context.Context, in *v1.RecordScoreRequest, opts ...grpc.CallOption) (*v1.RecordScoreResponse, error)
	// 批量覆盖设置榜单分数（历史回填等一次性全量摄入场景）。
	// prune_others=true 时移除快照中已不存在的成员（如粉丝归零的用户），仅当 batch 为完整快照时开启。
	BatchSetScore(ctx context.Context, in *v1.BatchSetScoreRequest, opts ...grpc.CallOption) (*v1.BatchSetScoreResponse, error)
	// 业务方注册榜单配置：声明如何展示该 board（decorator）+ 是否跳转（link_template）。
	// ranking-service 仅按配置行事，新增任何榜单都无需改动核心代码。
	RegisterBoard(ctx context.Context, in *v1.RegisterBoardRequest, opts ...grpc.CallOption) (*v1.RegisterBoardResponse, error)
}

type rankingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingServiceClient(cc grpc.ClientConnInterface) RankingServiceClient {
	return &rankingServiceClient{cc}
}

func (c *rankingServiceClient) RecordScore(ctx context.Context, in *v1.RecordScoreRequest, opts ...grpc.CallOption) (*v1.RecordScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RecordScoreResponse)
	err := c.cc.Invoke(ctx, RankingService_RecordScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) BatchSetScore(ctx context.Context, in *v1.BatchSetScoreRequest, opts ...grpc.CallOption) (*v1.BatchSetScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.BatchSetScoreResponse)
	err := c.cc.Invoke(ctx, RankingService_BatchSetScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingServiceClient) RegisterBoard(ctx context.Context, in *v1.RegisterBoardRequest, opts ...grpc.CallOption) (*v1.RegisterBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.RegisterBoardResponse)
	err := c.cc.Invoke(ctx, RankingService_RegisterBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServiceServer is the server API for RankingService service.
// All implementations must embed UnimplementedRankingServiceServer
// for forward compatibility.
//
// RankingService 内部摄入接口（ranking.v0，仅内网、仅受信服务）：
// 业务方（article/comment/user）推送分数变更 + 声明榜单展示配置。
type RankingServiceServer interface {
	// 推送分数变更（增量或绝对值）。
	RecordScore(context.Context, *v1.RecordScoreRequest) (*v1.RecordScoreResponse, error)
	// 批量覆盖设置榜单分数（历史回填等一次性全量摄入场景）。
	// prune_others=true 时移除快照中已不存在的成员（如粉丝归零的用户），仅当 batch 为完整快照时开启。
	BatchSetScore(context.Context, *v1.BatchSetScoreRequest) (*v1.BatchSetScoreResponse, error)
	// 业务方注册榜单配置：声明如何展示该 board（decorator）+ 是否跳转（link_template）。
	// ranking-service 仅按配置行事，新增任何榜单都无需改动核心代码。
	RegisterBoard(context.Context, *v1.RegisterBoardRequest) (*v1.RegisterBoardResponse, error)
	mustEmbedUnimplementedRankingServiceServer()
}

// UnimplementedRankingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankingServiceServer struct{}

func (UnimplementedRankingServiceServer) RecordScore(context.Context, *v1.RecordScoreRequest) (*v1.RecordScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordScore not implemented")
}
func (UnimplementedRankingServiceServer) BatchSetScore(context.Context, *v1.BatchSetScoreRequest) (*v1.BatchSetScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSetScore not implemented")
}
func (UnimplementedRankingServiceServer) RegisterBoard(context.Context, *v1.RegisterBoardRequest) (*v1.RegisterBoardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBoard not implemented")
}
func (UnimplementedRankingServiceServer) mustEmbedUnimplementedRankingServiceServer() {}
func (UnimplementedRankingServiceServer) testEmbeddedByValue()                        {}

// UnsafeRankingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingServiceServer will
// result in compilation errors.
type UnsafeRankingServiceServer interface {
	mustEmbedUnimplementedRankingServiceServer()
}

func RegisterRankingServiceServer(s grpc.ServiceRegistrar, srv RankingServiceServer) {
	// If the following call panics, it indicates UnimplementedRankingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankingService_ServiceDesc, srv)
}

func _RankingService_RecordScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RecordScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).RecordScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_RecordScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).RecordScore(ctx, req.(*v1.RecordScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_BatchSetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.BatchSetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).BatchSetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_BatchSetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).BatchSetScore(ctx, req.(*v1.BatchSetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RankingService_RegisterBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RegisterBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).RegisterBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingService_RegisterBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).RegisterBoard(ctx, req.(*v1.RegisterBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankingService_ServiceDesc is the grpc.ServiceDesc for RankingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ranking.v0.RankingService",
	HandlerType: (*RankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordScore",
			Handler:    _RankingService_RecordScore_Handler,
		},
		{
			MethodName: "BatchSetScore",
			Handler:    _RankingService_BatchSetScore_Handler,
		},
		{
			MethodName: "RegisterBoard",
			Handler:    _RankingService_RegisterBoard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ranking_ingest.proto",
}
